spring:
  config:
    import: classpath:test.yml,classpath:cache.yml
  auth:
    host: https://dfidveri.market.alicloudapi.com
    path: /verify_id_name
    appcode: xxxx
  oss:
    enabled: true
    bucket: nfturbo-file
    endPoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKey: xxxx
    accessSecret: xxxx