spring:
  elasticsearch:
    enable: false #如果你要使用es，这里需要改成true
    uris: http://47.102.86.181:9200 #如果你没有启动一键mock，这里需要改成你自己的
    username: elastic #如果你没有启动一键mock，这里需要改成你自己的
    password: 123456 #如果你没有启动一键mock，这里需要改成你自己的
easy-es:
  enable: false
  address : 47.102.86.181:9200 #如果你没有启动一键mock，这里需要改成你自己的
  username: elastic #如果你没有启动一键mock，这里需要改成你自己的
  password: 123456 #如果你没有启动一键mock，这里需要改成你自己的