spring:
  data:
    redis:
      host: 116.205.170.187 #首次启动前务必修改成你自己的
      port: 6379 # Redis服务器连接端口 #首次启动前务必修改成你自己的
      password: '123456' # Redis服务器连接密码（默认为空） #首次启动前务必修改成你自己的
      ssl:
        enabled: true
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: '123456'  #首次启动前务必修改成你自己的
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://116.205.170.187:6379"   #首次启动前务必修改成你自己的
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      keyPrefix: ${spring.application.name}
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000