spring:
  profiles:
    active: prod
  application:
    name: @application.name@
  config:
    import: classpath:datasource.yml,classpath:rpc.yml,classpath:cache.yml,classpath:stream.yml
  cloud:
    function:
      definition: chain
    stream:
      bindings:
        chain-out-0:
          content-type: application/json
          destination: chain-result-topic
          group: chain-group
          binder: rocketmq

server:
  port: 8085

