spring:
  application:
    name: dp-nft-gateway
  config:
    import: classpath:cache.yml,classpath:config.yml,classpath:limiter.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: dp-nft-auth
          uri: lb://dp-nft-auth
          predicates:
            - Path=/auth/**,/token/**
        - id: dp-nft-business
          uri: lb://dp-nft-business
          predicates:
            - Path=/trade/**,/order/**,/user/**,/collection/**,/wxPay/**
server:
  port: 8081
